### PR TITLE
Prioritize  user specified value

### PR DESCRIPTION
**Pull request by momielab**
In local development,  user-specified port value is always disregarded, **if `PORT` is set**

```bash
$(npm bin)/mocha -r spec/global.js spec/lib/loopback-server.coffee
```
results:
```bash
Browse your REST API at http://localhost:3001/explorer
Web server listening at: http://localhost:3001/
```

but if `PORT` is set, printed like below:

```bash
PORT=4444 $(npm bin)/mocha -r spec/global.js spec/lib/loopback-server.coffee
```

```bash
  LoopbackServer
    launch
Browse your REST API at http://localhost:4444/explorer
Web server listening at: http://localhost:4444/
LOOPBACK_WITH_ADMIN_STARTED
Admin token will be refreshed every 12 hours.
      ✓ runs loopback in the same process (1490ms)

  1 passing (2s)
```

This PR changes prioritize  order

1. user specified value
2. value of `PORT`
3. `3000`( default value of this package)

### CODE REVIEW

**Comment by momielab** [comment]
closes https://github.com/CureApp/nash/issues/203

**Comment by januswel** [comment]
@momielab 
Would you add some test cases?

- with the var `PORT`
- with no settings, so loopback will be launched at port 3000

**Comment by januswel** [comment]
on other codes, LGTM!!
lgtm-yuta-look-up

**Comment by januswel** [comment]
thx!!
It's so beautiful

**Pull request merged**
